### ISSUE TITLE
Cannot read property lookup of undefined 

### ISSUE THREAD

**Issue by clentoo** [firebase/firebase-tools-ui#505]
I am trying to use Cloud functions to work on payment authentication with stripe in an e-commerce store project. The code for the index.js file after installing functions using firebase CLI goes thus:
const functions = require("firebase-functions");
const express = require("express");
const cors = require("cors");

// API

// App Config
const app = express();

// Middlewares
app.use(cors({origin: true}));
app.use(express.json());
app.use(express.static("public"));

// API routes
app.get("/api/",
    (request, response) => response.status(200).send("hello world"));

// Listen Command
exports.api = functions.https.onRequest(app);

To emulate before deploying I run firebase emulators:start in the command line and get this error immediately I click on the link to access the emulator UI in chrome:

TypeError: Cannot read property 'lookup' of undefined
    at ServerResponse.header (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:766:37)
    at ServerResponse.json (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:264:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\hub.js:29:17
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)

**Comment by yuchenshi** [comment]
Would you mind upgrading Firebase CLI and retry? If it still doesn't work, please let us know the CLI version and Node.js version.

```bash
npm install -g firebase-tools@latest

# try again, and if it doesn't work, note the versions:

firebase --version
node --version
```

**Comment by clentoo** [comment]
Just upgraded it to the latest which is 9.4.0 and got the same error. The firebase version is 9.4.0 and the node version is 12.18.0.

The UI-debug.log says this:
d [FetchError]: invalid json response body at http://localhost:4400/emulators reason: Unexpected token < in JSON at position 0
    at C:\Users\user\.cache\firebase\emulators\ui-v1.4.1\server.bundle.js:326:7333
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async o (C:\Users\user\.cache\firebase\emulators\ui-v1.4.1\server.bundle.js:154:2911) {
  type: 'invalid-json'
}

And the package.json file in the functions folder is this:
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "12"
  },
  "main": "index.js",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "firebase-admin": "^9.2.0",
    "firebase-functions": "^3.11.0",
    "stripe": "^8.135.0"
  },
  "devDependencies": {
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}

**Comment by yuchenshi** [comment]
Thanks! Could you please also do me a favor and post the `firebase-debug.log` file please? You can add it as an attachment if it gets too long.

One other thing to try is to actually go to `http://localhost:4400/emulators` in browser (or use `curl`) while it's running to see what is the actual response. We now know it's not JSON, but what is it then?

**Comment by clentoo** [comment]
Here's what I got in http://localhost:4400/emulators:

TypeError: Cannot read property 'lookup' of undefined
    at ServerResponse.header (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:766:37)
    at ServerResponse.json (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:264:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\hub.js:29:17
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
[firebase-debug.log](https://github.com/firebase/firebase-tools-ui/files/6012803/firebase-debug.log)
