### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by nyambayar1231** [firebase/firebase-tools-ui#511]
>  events.js:292
>        throw er; // Unhandled 'error' event
>        ^
>
>  Error: connect ECONNREFUSED 0.0.0.0:9500
>      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
>  Emitted 'error' event on Session instance at:
>      at Socket.<anonymous> (D:\CloudFunction\functions\node_modules\smpp\lib\smpp.js:48:8)
>      at Socket.emit (events.js:315:20)
>      at emitErrorNT (internal/streams/destroy.js:106:8)
>      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
>      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>    errno: -4078,
>    code: 'ECONNREFUSED',
>    syscall: 'connect',
>    address: '0.0.0.0',
>    port: 9500
>  }

**Comment by nyambayar1231** [comment]
sorry
