### ISSUE TITLE
White screen of death in Firestore Emulator request log

### ISSUE THREAD

**Issue by Daspy11** [firebase/firebase-tools-ui#835]
**Describe the bug**
Something is causing the firestore emulator "requests" tab to crash with a whitescreen of death

**To Reproduce**
Very difficult to say, likely to due to logic buried deep in the firestore emulators. I'm not able to reproduce a minimally broken example, but something is causing very broken behaviour.

**Expected behavior**
The requests UI renders as expected

**Screenshots**
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/24847059/181105202-5cadcfea-cced-4ae5-a9f1-a530b3eab2c6.png">

**Desktop (please complete the following information):**

- OS: MacOS 10.X, Windows 10
- Browser: Chrome, Brave
- Version: Latest

**Additional context**
There's some kind of context issue at fault here, but the whole "white screen of death" thing makes this rather difficult to troubleshoot since by nature these kinds of errors are not catchable.

**Comment by sdmoir** [comment]
I'm experiencing this issue as well:
- Device: M2 MacBook Air
- OS: MacOS 12.6
- Browser: Chrome
- Version: Latest

Same error in my browser console that was posted in the screenshot above:
```
react-dom.production.min.js:186 TypeError: Cannot read properties of undefined (reading 'method')
    at pze (TableRow.tsx:49:33)
    at mze (TableRow.tsx:78:7)
    at PD (react-dom.production.min.js:166:137)
    at cj (react-dom.production.min.js:289:386)
    at aj (react-dom.production.min.js:279:389)
    at ole (react-dom.production.min.js:279:320)
    at bE (react-dom.production.min.js:279:180)
    at VR (react-dom.production.min.js:270:88)
    at E5 (react-dom.production.min.js:272:300)
    at Lh (react-dom.production.min.js:127:105)
LR @ react-dom.production.min.js:186
n.callback @ react-dom.production.min.js:187
JB @ react-dom.production.min.js:137
x5 @ react-dom.production.min.js:260
tj @ react-dom.production.min.js:258
nle @ react-dom.production.min.js:257
sle @ react-dom.production.min.js:282
Ep @ react-dom.production.min.js:280
E5 @ react-dom.production.min.js:272
Lh @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:266
```
