### ISSUE TITLE
Emulator services start failing randomly and client suddenly tries to connect to 0.0.0.0

### ISSUE THREAD

**Issue by muzzah** [firebase/firebase-tools-ui#934]
**Describe the bug**
Emulator client works but then start to fail connecting to emulators as it starts to try to connect to IP 0.0.0.0.

```
D/WebSocket( 5724): ws_1 - WebSocket error.
D/WebSocket( 5724): com.google.firebase.database.tubesock.WebSocketException: error while creating socket to ws://0.0.0.0:5002/.ws?ns=local&v=5&ls=6T508Gbvs3huGUmy8cKrtYGtAnKycM2x
D/WebSocket( 5724): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:301)
D/WebSocket( 5724): 	at com.google.firebase.database.tubesock.WebSocket.runReader(WebSocket.java:360)
D/WebSocket( 5724): 	at com.google.firebase.database.tubesock.WebSocket.access$000(WebSocket.java:47)
D/WebSocket( 5724): 	at com.google.firebase.database.tubesock.WebSocket$2.run(WebSocket.java:143)
D/WebSocket( 5724): 	at java.lang.Thread.run(Thread.java:761)
D/WebSocket( 5724): Caused by: java.net.ConnectException: Connection refused
D/WebSocket( 5724): 	at java.net.PlainSocketImpl.socketConnect(Native Method)
D/WebSocket( 5724): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
D/WebSocket( 5724): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:194)
D/WebSocket( 5724): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
D/WebSocket( 5724): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
D/WebSocket( 5724): 	at java.net.Socket.connect(Socket.java:586)
D/WebSocket( 5724): 	at java.net.Socket.connect(Socket.java:535)
D/WebSocket( 5724): 	at java.net.Socket.<init>(Socket.java:427)
D/WebSocket( 5724): 	at java.net.Socket.<init>(Socket.java:210)
D/WebSocket( 5724): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:297)
D/WebSocket( 5724): 	... 4 more
D/WebSocket( 5724): ws_1 - closing itself
```

**To Reproduce**
It happens after a hot restart on the flutter app through the IDE generally

**Expected behavior**
The emulator shold continue to try to connect to the specified IP as per configuration

**Smartphone (please complete the following information):**
- OS: MacOS 13.2.1
- Pixel XL and C emulators running Nougat
- Using firebase cli 11.25.1

**Additional context**

- I am configuring firebase through code only. Specifying use Emulator as needed on the firebase instances and passing the hostname that resolves to the IP that the emulators are running on
- After a fresh install it seems to work but then fails connect to the emualtors
- Emulators are running on a remote dev server that has 2 IPs (192. and 10.) and is accessed through a hostname that resolves to both of these IPs
- I also see the browser trying to connect to 0.0.0.0 at times
- This seem to start to happen after enabling Auth emulator. 

My firebase config

```
{
  "firestore": {
    "rules": "firestore.rules"
  },
  "emulators": {
    "singleProjectMode": false,	  
    "firestore": {
      "port": 5000,
      "host": "0.0.0.0",
      "indexes": "firestore-indexes.json"
    },
    "auth": {
      "port": "5001",
      "host": "0.0.0.0"
    },
    "database": {
      "port": "5002",
      "host": "0.0.0.0"
    },
    "logging": {
      "host": "0.0.0.0"
    },
    "hub": {
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 4000
    }
  }
}
```

**Comment by muzzah** [comment]
Closing, resolved
