### ISSUE TITLE
Error in firebase deploy

### ISSUE THREAD

**Issue by gelocaindoy** [firebase/firebase-tools-ui#941]
Windows 11 OS
firebase version 11.28.0
Terminal Powershell

=== Deploying to 'grocery-5c135'...

i  deploying firestore, functions
Running command: npm --prefix %RESOURCE_DIR% run lint
npm ERR! Missing script: "lint"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm link # Symlink a package folder
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\IvyGelo\AppData\Local\npm-cache\_logs\2023-04-23T11_40_40_791Z-debug.log
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix C:\Users\IvyGelo\Downloads\1.6.62\glover-autoassignment-firebase-function-main\functions run lint ENOENT
    at notFoundError (C:\Users\IvyGelo\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\IvyGelo\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\IvyGelo\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\IvyGelo\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm --prefix C:\\Users\\IvyGelo\\Downloads\\1.6.62\\autoassignment-firebase-function-main\\functions run lint',
  path: 'npm --prefix C:\\Users\\IvyGelo\\Downloads\\1.6.62\\autoassignment-firebase-function-main\\functions run lint',
  spawnargs: []
}

**Comment by christhompsongoogle** [comment]
Hi [gelocaindoy](https://github.com/gelocaindoy), can you provide a repro case for this one?

**Comment by christhompsongoogle** [comment]
Bump
